MOCK_PURCHASE_HISTORIES = [
    # ── 기존 데이터 (naver 플랫폼) ─────────────────────────────────
    {'id': 4, 'user_id': 1, 'product_id': 7, 'product_option_id': 3, 'product_name': 'Fresh strawberry 500g', 'brand': 'BerryFarm', 'category': 'fruit', 'option_text': '500g', 'selected_options': {'size': '500g'}, 'price_at_purchase': 10900, 'quantity': 1, 'total_price': 10900, 'platform': 'naver', 'product_url': 'https://example.com/product/7', 'purchased_at': '2026-05-20T10:00:00', 'satisfaction_score': 5, 'memo': 'ambiguous reorder test candidate', 'keyword': 'strawberry'},
    {'id': 5, 'user_id': 1, 'product_id': 8, 'product_option_id': 4, 'product_name': 'Frozen strawberry 1kg', 'brand': 'BerryFarm', 'category': 'fruit', 'option_text': '1kg', 'selected_options': {'size': '1kg'}, 'price_at_purchase': 8900, 'quantity': 1, 'total_price': 8900, 'platform': 'naver', 'product_url': 'https://example.com/product/8', 'purchased_at': '2026-05-20T10:05:00', 'satisfaction_score': 5, 'memo': 'ambiguous reorder test candidate', 'keyword': 'strawberry'},
    {'id': 1, 'user_id': 1, 'product_id': 1, 'product_option_id': 1, 'product_name': '설향 딸기 500g', 'brand': '설향', 'category': 'fruit', 'option_text': '500g', 'selected_options': {'용량': '500g'}, 'price_at_purchase': 9900, 'quantity': 1, 'total_price': 9900, 'platform': 'naver', 'product_url': 'https://example.com/product/1', 'purchased_at': '2026-04-10T10:00:00', 'satisfaction_score': 5, 'memo': '맛있게 먹음', 'keyword': 'strawberry'},
    {'id': 2, 'user_id': 1, 'product_id': 4, 'product_option_id': None, 'product_name': '국산 참기름 300ml', 'brand': 'CJ', 'category': 'condiment', 'option_text': '300ml', 'selected_options': {'용량': '300ml'}, 'price_at_purchase': 8000, 'quantity': 1, 'total_price': 8000, 'platform': 'naver', 'product_url': 'https://example.com/product/4', 'purchased_at': '2026-04-20T10:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': 'sesame_oil'},
    {'id': 3, 'user_id': 1, 'product_id': 6, 'product_option_id': 2, 'product_name': '검은콩 두유 190ml 24팩', 'brand': '정식품', 'category': 'beverage', 'option_text': '190ml 24팩', 'selected_options': {'용량': '190ml 24팩'}, 'price_at_purchase': 18000, 'quantity': 1, 'total_price': 18000, 'platform': 'naver', 'product_url': 'https://example.com/product/6', 'purchased_at': '2026-04-25T10:00:00', 'satisfaction_score': 4, 'memo': None, 'keyword': 'soy_milk'},

    # ── 컬리 신선식품 ────────────────────────────────────────────
    {'id': 18, 'user_id': 1, 'product_id': 10, 'product_option_id': None, 'product_name': '[조인] 동물복지 백색 유정 초란 10구', 'brand': '컬리', 'category': '달걀', 'option_text': '10구', 'selected_options': {'수량': '10구'}, 'price_at_purchase': 4608, 'quantity': 1, 'total_price': 4608, 'platform': 'kurly', 'product_url': 'https://www.kurly.com/goods/5054981', 'purchased_at': '2026-04-05T09:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '달걀'},
    {'id': 6, 'user_id': 1, 'product_id': 10, 'product_option_id': None, 'product_name': '[조인] 동물복지 백색 유정 초란 10구', 'brand': '컬리', 'category': '달걀', 'option_text': '10구', 'selected_options': {'수량': '1구'}, 'price_at_purchase': 4608, 'quantity': 1, 'total_price': 4608, 'platform': 'kurly', 'product_url': 'https://www.kurly.com/goods/5054981', 'purchased_at': '2026-05-01T09:00:00', 'satisfaction_score': 5, 'memo': '신선함 좋음', 'keyword': '달걀'},
    {'id': 7, 'user_id': 1, 'product_id': 11, 'product_option_id': None, 'product_name': '풀무원 국산콩 두부 (부침) 300g', 'brand': '풀무원', 'category': '두부', 'option_text': '300g', 'selected_options': {'용량': '300g'}, 'price_at_purchase': 2490, 'quantity': 2, 'total_price': 4980, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000047752', 'purchased_at': '2026-04-28T10:30:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '두부'},
    {'id': 8, 'user_id': 1, 'product_id': 12, 'product_option_id': None, 'product_name': '[컬리] 제주 무농약 당근 500g', 'brand': '컬리', 'category': '채소', 'option_text': '500g', 'selected_options': {'용량': '500g'}, 'price_at_purchase': 3900, 'quantity': 1, 'total_price': 3900, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000108152', 'purchased_at': '2026-04-15T08:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '당근'},
    {'id': 9, 'user_id': 1, 'product_id': 13, 'product_option_id': None, 'product_name': '국내산 브로콜리 1개', 'brand': None, 'category': '채소', 'option_text': '1개', 'selected_options': {'수량': '1개'}, 'price_at_purchase': 2490, 'quantity': 1, 'total_price': 2490, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000100101', 'purchased_at': '2026-05-05T09:30:00', 'satisfaction_score': 4, 'memo': None, 'keyword': '브로콜리'},
    {'id': 10, 'user_id': 1, 'product_id': 14, 'product_option_id': None, 'product_name': '[컬리] 어린잎 시금치 150g', 'brand': '컬리', 'category': '채소', 'option_text': '150g', 'selected_options': {'용량': '150g'}, 'price_at_purchase': 2990, 'quantity': 1, 'total_price': 2990, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000155210', 'purchased_at': '2026-05-10T09:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '시금치'},
    {'id': 11, 'user_id': 1, 'product_id': 15, 'product_option_id': None, 'product_name': '스위트마켓 바나나 1송이 (약 700g)', 'brand': '스위트마켓', 'category': '과일', 'option_text': '약 700g', 'selected_options': {'무게': '약 700g'}, 'price_at_purchase': 2990, 'quantity': 1, 'total_price': 2990, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000024682', 'purchased_at': '2026-05-12T08:00:00', 'satisfaction_score': 4, 'memo': None, 'keyword': '바나나'},

    # ── 컬리 냉동/간편식 ──────────────────────────────────────────
    {'id': 12, 'user_id': 1, 'product_id': 16, 'product_option_id': None, 'product_name': '비비고 왕교자 1.05kg', 'brand': 'CJ제일제당', 'category': '냉동식품', 'option_text': '1.05kg', 'selected_options': {'용량': '1.05kg'}, 'price_at_purchase': 11900, 'quantity': 1, 'total_price': 11900, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000011282', 'purchased_at': '2026-04-22T10:00:00', 'satisfaction_score': 5, 'memo': '재구매 의사 있음', 'keyword': '만두'},
    {'id': 13, 'user_id': 1, 'product_id': 17, 'product_option_id': None, 'product_name': '하림 IFF 닭가슴살 오리지널 100g×5', 'brand': '하림', 'category': '냉동식품', 'option_text': '100g×5', 'selected_options': {'수량': '5팩'}, 'price_at_purchase': 7900, 'quantity': 1, 'total_price': 7900, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000044601', 'purchased_at': '2026-05-03T11:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '닭가슴살'},
    {'id': 14, 'user_id': 1, 'product_id': 18, 'product_option_id': None, 'product_name': '오뚜기 맛있는 함박스테이크 130g×4', 'brand': '오뚜기', 'category': '냉동식품', 'option_text': '130g×4', 'selected_options': {'수량': '4개'}, 'price_at_purchase': 9500, 'quantity': 1, 'total_price': 9500, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000044321', 'purchased_at': '2026-04-30T12:00:00', 'satisfaction_score': 4, 'memo': None, 'keyword': '함박스테이크'},
    {'id': 15, 'user_id': 1, 'product_id': 19, 'product_option_id': None, 'product_name': '농심 신라면 5개입', 'brand': '농심', 'category': '라면', 'option_text': '120g×5', 'selected_options': {'수량': '5개입'}, 'price_at_purchase': 4500, 'quantity': 1, 'total_price': 4500, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000083810', 'purchased_at': '2026-04-18T14:00:00', 'satisfaction_score': 5, 'memo': None, 'keyword': '라면'},
    {'id': 16, 'user_id': 1, 'product_id': 20, 'product_option_id': None, 'product_name': '프레시지 고기 듬뿍 순두부찌개 밀키트 2인', 'brand': '프레시지', 'category': '밀키트', 'option_text': '2인분 (약 480g)', 'selected_options': {'인분': '2인'}, 'price_at_purchase': 6900, 'quantity': 1, 'total_price': 6900, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000044889', 'purchased_at': '2026-05-08T11:30:00', 'satisfaction_score': 4, 'memo': None, 'keyword': '순두부찌개'},
    {'id': 17, 'user_id': 1, 'product_id': 21, 'product_option_id': None, 'product_name': '[컬리] 닭갈비 볶음밥 220g×3', 'brand': '컬리', 'category': '냉동식품', 'option_text': '220g×3', 'selected_options': {'수량': '3개'}, 'price_at_purchase': 8900, 'quantity': 1, 'total_price': 8900, 'platform': 'kurly', 'product_url': 'https://mock.kurly.com/goods/1000089743', 'purchased_at': '2026-05-15T12:00:00', 'satisfaction_score': 5, 'memo': '또 시킬 것 같음', 'keyword': '닭갈비볶음밥'},

    # ── 기타 ─────────────────────────────────────────────────
    {'id': 19, 'purchased_at': '2026-05-24T22:11:03.334909', 'user_id': 1, 'conversation_id': None, 'product_id': 10, 'product_option_id': None, 'product_name': '[조인] 동물복지 백색 유정 초란 10구', 'brand': None, 'category': None, 'option_text': '10구', 'selected_options': {'수량': '1구'}, 'product_url': 'https://www.kurly.com/goods/5054981', 'price_at_purchase': 4608, 'quantity': 1, 'total_price': 4608, 'platform': 'kurly', 'keyword': '달걀', 'satisfaction_score': None, 'memo': None},
    {'id': 20, 'purchased_at': '2026-05-24T22:18:50.001210', 'user_id': 1, 'conversation_id': None, 'product_id': 10, 'product_option_id': None, 'product_name': '[조인] 동물복지 백색 유정 초란 10구', 'brand': None, 'category': None, 'option_text': '10구', 'selected_options': {'수량': '1구'}, 'product_url': 'https://www.kurly.com/goods/5054981', 'price_at_purchase': 4608, 'quantity': 2, 'total_price': 9216, 'platform': 'kurly', 'keyword': '달걀', 'satisfaction_score': None, 'memo': None},
    {'id': 21, 'purchased_at': '2026-05-24T23:18:22.331590', 'user_id': 1, 'conversation_id': None, 'product_id': 10, 'product_option_id': None, 'product_name': '[조인] 동물복지 백색 유정 초란 10구', 'brand': None, 'category': None, 'option_text': '10구', 'selected_options': {'수량': '1구'}, 'product_url': 'https://www.kurly.com/goods/5054981', 'price_at_purchase': 4608, 'quantity': 1, 'total_price': 4608, 'platform': 'kurly', 'keyword': '달걀', 'satisfaction_score': None, 'memo': None},
]

