MOCK_RECOMMENDATIONS = [
    {"id": 10, "conversation_id": 42, "keyword": "strawberry", "status": "shown", "summary": "딸기 재구매 후보 추천"},
    {"id": 11, "conversation_id": 43, "keyword": "sesame_oil", "status": "shown", "summary": "참기름 재구매 후보 추천"},
    {"id": 12, "conversation_id": 44, "keyword": "soy_milk", "status": "shown", "summary": "두유 재구매 후보 추천"},
]

MOCK_RECOMMENDATION_ITEMS = [
    {"id": 101, "recommendation_id": 10, "product_id": 1, "product_name": "설향 딸기 500g", "brand": "설향", "price": 12000, "option_text": "500g", "delivery_info": "내일 도착 예정", "delivery_fee": 0, "rating": 4.8, "review_count": 1200, "image_url": "https://example.com/strawberry.jpg", "product_url": "https://example.com/product/1", "platform": "naver", "reason": "지난번에 만족도가 높았던 상품과 가장 비슷해요.", "rank": 1, "is_selected": False, "is_orderable": True, "order_block_reason": None},
    {"id": 102, "recommendation_id": 10, "product_id": 2, "product_name": "국산 딸기 750g", "brand": "농협", "price": 15000, "option_text": "750g", "delivery_info": "모레 도착 예정", "delivery_fee": 0, "rating": 4.5, "review_count": 800, "image_url": None, "product_url": None, "platform": "naver", "reason": "용량이 더 많고 가성비가 좋아요.", "rank": 2, "is_selected": False, "is_orderable": True, "order_block_reason": None},
    {"id": 103, "recommendation_id": 10, "product_id": 3, "product_name": "못난이 딸기 1kg", "brand": "못난이농장", "price": 10000, "option_text": "1kg", "delivery_info": None, "delivery_fee": 0, "rating": 4.2, "review_count": 300, "image_url": None, "product_url": None, "platform": "naver", "reason": None, "rank": 3, "is_selected": False, "is_orderable": False, "order_block_reason": "품절"},
    {"id": 104, "recommendation_id": 11, "product_id": 4, "product_name": "국산 참기름 300ml", "brand": "CJ", "price": 8000, "option_text": "300ml", "delivery_info": "내일 도착 예정", "delivery_fee": 0, "rating": 4.7, "review_count": 500, "image_url": None, "product_url": None, "platform": "naver", "reason": "지난번에 구매하신 상품이에요.", "rank": 1, "is_selected": False, "is_orderable": True, "order_block_reason": None},
    {"id": 105, "recommendation_id": 11, "product_id": 5, "product_name": "들기름 300ml", "brand": "오뚜기", "price": 9000, "option_text": "300ml", "delivery_info": "내일 도착 예정", "delivery_fee": 0, "rating": 4.6, "review_count": 400, "image_url": None, "product_url": None, "platform": "naver", "reason": "비슷한 카테고리의 인기 상품이에요.", "rank": 2, "is_selected": False, "is_orderable": True, "order_block_reason": None},
    {"id": 106, "recommendation_id": 12, "product_id": 6, "product_name": "검은콩 두유 190ml 24팩", "brand": "정식품", "price": 18000, "option_text": "190ml 24팩", "delivery_info": "내일 도착 예정", "delivery_fee": 0, "rating": 4.8, "review_count": 2000, "image_url": None, "product_url": None, "platform": "naver", "reason": "지난번에 구매하신 상품이에요.", "rank": 1, "is_selected": False, "is_orderable": True, "order_block_reason": None},
    {"id": 107, "recommendation_id": 12, "product_id": 7, "product_name": "무가당 두유 200ml 24팩", "brand": "삼육", "price": 16000, "option_text": "200ml 24팩", "delivery_info": "내일 도착 예정", "delivery_fee": 0, "rating": 4.5, "review_count": 1500, "image_url": None, "product_url": None, "platform": "naver", "reason": "무가당으로 더 건강해요.", "rank": 2, "is_selected": False, "is_orderable": True, "order_block_reason": None},
]
