"""create initial schema

Revision ID: 03ebc4ef2983
Revises:
Create Date: 2026-05-24 17:37:35.236986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "03ebc4ef2983"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create v0.4 business DB schema."""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_crawled_snapshot_id'], ['crawled_product_snapshots.id'], name='fk_products_last_crawled_snapshot_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_message_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawled_product_snapshots',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_product_id', sa.String(), nullable=True),
    sa.Column('external_product_url', sa.Text(), nullable=True),
    sa.Column('crawl_keyword', sa.String(), nullable=True),
    sa.Column('crawl_source', sa.String(), nullable=True),
    sa.Column('raw_product_name', sa.Text(), nullable=False),
    sa.Column('raw_brand', sa.String(), nullable=True),
    sa.Column('raw_category', sa.String(), nullable=True),
    sa.Column('raw_price', sa.String(), nullable=True),
    sa.Column('raw_original_price', sa.String(), nullable=True),
    sa.Column('raw_discount_rate', sa.String(), nullable=True),
    sa.Column('raw_delivery_info', sa.String(), nullable=True),
    sa.Column('raw_rating', sa.String(), nullable=True),
    sa.Column('raw_review_count', sa.String(), nullable=True),
    sa.Column('raw_image_url', sa.Text(), nullable=True),
    sa.Column('raw_is_sold_out', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('normalized_brand', sa.String(), nullable=True),
    sa.Column('normalized_category', sa.String(), nullable=True),
    sa.Column('normalized_sub_category', sa.String(), nullable=True),
    sa.Column('normalized_volume', sa.String(), nullable=True),
    sa.Column('normalized_price', sa.Integer(), nullable=True),
    sa.Column('normalized_original_price', sa.Integer(), nullable=True),
    sa.Column('normalized_discount_rate', sa.Float(), nullable=True),
    sa.Column('normalized_delivery_type', sa.String(), nullable=True),
    sa.Column('normalized_rating', sa.Float(), nullable=True),
    sa.Column('normalized_review_count', sa.Integer(), nullable=True),
    sa.Column('normalized_is_available', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('normalization_status', sa.String(), nullable=True),
    sa.Column('normalization_error', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_options',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.Column('option_value', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('additional_price', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_label', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_phone', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('delivery_request', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_naver_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('naver_user_id', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_events',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_intents',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_user_request', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('intent_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('pending_action_type', sa.String(), nullable=True),
    sa.Column('target_category', sa.String(), nullable=True),
    sa.Column('target_product_name', sa.String(), nullable=True),
    sa.Column('extracted_keywords', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_clarification', sa.Boolean(), nullable=True),
    sa.Column('clarification_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_api_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_product_mappings',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_option_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_product_id', sa.String(), nullable=True),
    sa.Column('external_option_id', sa.String(), nullable=True),
    sa.Column('external_product_url', sa.Text(), nullable=True),
    sa.Column('external_product_url_hash', sa.String(), nullable=True),
    sa.Column('mall_name', sa.String(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_address_snapshot', sa.Text(), nullable=True),
    sa.Column('address_confirmed', sa.Boolean(), nullable=False),
    sa.Column('total_product_price', sa.Integer(), nullable=True),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.Column('total_expected_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('intent_id', sa.BigInteger(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['agent_intents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('checkout_session_id', sa.BigInteger(), nullable=True),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=True),
    sa.Column('shipping_address_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_name_snapshot', sa.String(), nullable=True),
    sa.Column('recipient_phone_snapshot', sa.String(), nullable=True),
    sa.Column('shipping_address_snapshot', sa.Text(), nullable=True),
    sa.Column('delivery_request_snapshot', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_product_price', sa.Integer(), nullable=False),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.Column('total_payment_amount', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['user_addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('external_payment_id', sa.String(), nullable=True),
    sa.Column('approval_number', sa.String(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('naver_order_mappings',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('naver_order_id', sa.String(), nullable=True),
    sa.Column('naver_product_order_id', sa.String(), nullable=True),
    sa.Column('naver_payment_id', sa.String(), nullable=True),
    sa.Column('naver_pay_order_key', sa.String(), nullable=True),
    sa.Column('naver_status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_histories',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_option_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('external_order_id', sa.String(), nullable=True),
    sa.Column('external_product_order_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=False),
    sa.Column('option_snapshot', sa.String(), nullable=True),
    sa.Column('brand_snapshot', sa.String(), nullable=True),
    sa.Column('category_snapshot', sa.String(), nullable=True),
    sa.Column('price_at_purchase', sa.Integer(), nullable=False),
    sa.Column('product_url_snapshot', sa.Text(), nullable=True),
    sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_items',
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_option_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_purchase_history_id', sa.BigInteger(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=False),
    sa.Column('brand_snapshot', sa.String(), nullable=True),
    sa.Column('category_snapshot', sa.String(), nullable=True),
    sa.Column('option_snapshot', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('price_at_recommendation', sa.Integer(), nullable=True),
    sa.Column('original_price_snapshot', sa.Integer(), nullable=True),
    sa.Column('discount_rate_snapshot', sa.Float(), nullable=True),
    sa.Column('delivery_fee', sa.Integer(), nullable=True),
    sa.Column('delivery_info_snapshot', sa.String(), nullable=True),
    sa.Column('rating_snapshot', sa.Float(), nullable=True),
    sa.Column('review_count_snapshot', sa.Integer(), nullable=True),
    sa.Column('product_url_snapshot', sa.Text(), nullable=True),
    sa.Column('image_url_snapshot', sa.Text(), nullable=True),
    sa.Column('is_presented', sa.Boolean(), nullable=False),
    sa.Column('presented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_orderable', sa.Boolean(), nullable=False),
    sa.Column('order_block_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['matched_purchase_history_id'], ['purchase_histories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_option_id', sa.BigInteger(), nullable=True),
    sa.Column('recommendation_item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Integer(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(), nullable=False),
    sa.Column('option_snapshot', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_option_id', sa.BigInteger(), nullable=True),
    sa.Column('recommendation_item_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(), nullable=False),
    sa.Column('option_snapshot', sa.String(), nullable=True),
    sa.Column('product_url_snapshot', sa.Text(), nullable=True),
    sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('external_product_order_id', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_conversations_langgraph_thread_id'), 'conversations', ['langgraph_thread_id'], unique=False)
    op.create_index(op.f('ix_conversations_stage'), 'conversations', ['stage'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_crawled_product_snapshots_platform'), 'crawled_product_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_naver_accounts_user_id'), 'user_naver_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_events_agent_name'), 'agent_events', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_events_conversation_id'), 'agent_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_intents_conversation_id'), 'agent_intents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_intents_user_id'), 'agent_intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_carts_status'), 'carts', ['status'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_external_api_logs_provider'), 'external_api_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_external_product_mappings_platform'), 'external_product_mappings', ['platform'], unique=False)
    op.create_index(op.f('ix_external_product_mappings_product_id'), 'external_product_mappings', ['product_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_idempotency_key'), 'checkout_sessions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_status'), 'checkout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_user_id'), 'checkout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_conversation_id'), 'recommendations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_naver_order_mappings_order_id'), 'naver_order_mappings', ['order_id'], unique=False)
    op.create_index(op.f('ix_purchase_histories_user_id'), 'purchase_histories', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_recommendation_id'), 'recommendation_items', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_foreign_key('fk_products_last_crawled_snapshot_id', 'products', 'crawled_product_snapshots', ['last_crawled_snapshot_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop v0.4 business DB schema."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_last_crawled_snapshot_id', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_index(op.f('ix_recommendation_items_recommendation_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_purchase_histories_user_id'), table_name='purchase_histories')
    op.drop_index(op.f('ix_naver_order_mappings_order_id'), table_name='naver_order_mappings')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_conversation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_checkout_sessions_user_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_status'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_idempotency_key'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_external_product_mappings_product_id'), table_name='external_product_mappings')
    op.drop_index(op.f('ix_external_product_mappings_platform'), table_name='external_product_mappings')
    op.drop_index(op.f('ix_external_api_logs_provider'), table_name='external_api_logs')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_status'), table_name='carts')
    op.drop_index(op.f('ix_agent_intents_user_id'), table_name='agent_intents')
    op.drop_index(op.f('ix_agent_intents_conversation_id'), table_name='agent_intents')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_conversation_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_name'), table_name='agent_events')
    op.drop_index(op.f('ix_user_naver_accounts_user_id'), table_name='user_naver_accounts')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_product_options_product_id'), table_name='product_options')
    op.drop_index(op.f('ix_crawled_product_snapshots_platform'), table_name='crawled_product_snapshots')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_stage'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_langgraph_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('recommendation_items')
    op.drop_table('purchase_histories')
    op.drop_table('naver_order_mappings')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('recommendations')
    op.drop_table('checkout_sessions')
    op.drop_table('external_product_mappings')
    op.drop_table('external_api_logs')
    op.drop_table('conversation_messages')
    op.drop_table('carts')
    op.drop_table('agent_intents')
    op.drop_table('agent_events')
    op.drop_table('user_naver_accounts')
    op.drop_table('user_addresses')
    op.drop_table('product_options')
    op.drop_table('crawled_product_snapshots')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
